name: Build and Test

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - '**'

jobs:
  build:
    permissions:
      checks: write

    name: Build and test
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
    
    - name: Run check style
      if: always()
      uses: nikitasavinov/checkstyle-action@master      
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
        fail_on_error: true
        level: info
        checkstyle_config: 'sun_checks.xml'
        # workdir: 'src/main/'

    - name: Run the JaCoCo report
      if: always()
      run: mvn --batch-mode --update-snapshots jacoco:report

    - name: Unit Test Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: '**/surefire-reports/TEST-*.xml'
        token: ${{ secrets.GITHUB_TOKEN }}
        check_name: 'Unit Test Report'
        fail_on_failure: true
        require_tests: true
        include_passed: true
        job_summary: true
        detailed_summary: false
        annotate_notice: false
        check_retries: true        
    
    - name: Code Coverage Report
      id: jacoco_reporter
      if: always()
      uses: PavanMudigonda/jacoco-reporter@v4.8
      with:
        coverage_results_path: 'target/site/jacoco/jacoco.xml'
        coverage_report_name: Coverage
        coverage_report_title: JaCoCo
        github_token: ${{ secrets.GITHUB_TOKEN }}
        skip_check_run: false
        minimum_coverage: 100
        fail_below_threshold: true
        publish_only_summary: false
